### ISSUE TITLE
Poll not Displaying on Elgg3.2

### ISSUE THREAD

**Issue by Ngseri** [ColdTrick/poll#13]
I am using the Poll plugin on my website currently running on Elgg2.3 and it works great. But when I visit poll pages on Elgg3.2 (mysite/poll/view/poll_guid), it does not display the poll content. Poll version 4.0 is the one I use on Elgg3.2.

**Comment by jeabakker** [comment]
please try version 4.2
> fixed: return a no results text if there are no votes on poll details

maybe that's an issue

**Comment by Ngseri** [comment]
Thank you. I tried **Poll 4.2** and learn that even polls created in Elgg2.3 with votes, it still displays only '**No vote has been cast yet**'.

Also, I just noticed that polls created in Elgg2.3 display differently from polls created in Elgg3.2.

Below poll was created in Elgg2.3
![Screen Shot 2020-02-21 at 8 48 57 AM](https://user-images.githubusercontent.com/8534322/75039705-371a2580-5487-11ea-968f-6c90c70a1816.png)

Below poll was created in Elgg3.2
![Screen Shot 2020-02-21 at 8 46 46 AM](https://user-images.githubusercontent.com/8534322/75039667-21a4fb80-5487-11ea-87fd-7975c44b4db4.png)

One other issue is that after casting a vote, when I visit that poll, it throws Javascript error complaining about chartjs. So, I did further research and found out poll/elgg-plugin.php refers to **chartjs** library in vendor/npm-asset directory. But **chartjs** does not exist there in Elgg3.2.

**Comment by Ngseri** [comment]
**Correction to previous comment**
First attachment is the poll created in Elgg3.2 and the second in Elgg2.3

**Comment by jeabakker** [comment]
How did you install the plugin?
- using composer
- zip download from community
- zip download from github (if so, did you use the 'source code' zip of the 'poll_v4.2zip')

If chart.js isn't installed in either `webroot/vendor` or `webroot/mod/poll/vendor` that explains the problem. The github source zip doesn't have all dependencies, the 'poll_v4.2.zip' does have it.
Or if you install using composer, that should also download the correct version and install it.

This is how it looks on my PC
![afbeelding](https://user-images.githubusercontent.com/881958/75043553-9183a800-54c0-11ea-8f34-c48999f0eaf4.png)

**Comment by Ngseri** [comment]
I chose poll 4.2 and ran git clone it using HTTPS approach. How can I run composer install poll plugin?
Thanks so much!

**Comment by jeabakker** [comment]
go to the `/mod/poll` folder and run `composer install --no-dev`

**Comment by Ngseri** [comment]
Awesome! Thanks jeabakker! 
I just learned that why polls created in Elgg2.3 look different from Elgg3.2. In my Elgg2.3 site, I use Poll version 2.3.4 and the poll objects do not have **answers** metadata like Poll version 4.*
